### PR TITLE
Bug fixes on upgradeDb

### PR DESCRIPTION
**Pull request by noelrv**
Fix bugs: 1) Unable to create new store on upgradeDb; 2) Unable to delete obsolete stores - present in old db version but not in new db version. Code refactor.

### CODE REVIEW

**Comment by amuste** [comment]
Thanks @noelrv  for the contribution

**Comment by noelrv** [comment]
It's the least that I can do @amuste.  I have put DnetIndexedDb to good use in a free app that I am working on. Thank you for sharing.

**Comment by Kylar182** [comment]
> It's the least that I can do @amuste. I have put DnetIndexedDb to good use in a free app that I am working on. Thank you for sharing.

We're all using it heavily and it's growing well. Thanks to @amuste and people like you. Gonna sub to this so I see the release on Nuget

**Comment by amuste** [comment]
Thanks @Kylar182. The new version is already published

**Pull request merged**
